package sd.rastreamentos.gui;

import ws.soap.Posicao;
import ws.soap.Veiculo;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import sd.rastreamentos.soap.AddVeiculo;
import sd.rastreamentos.soap.AlteraVeiculoID;
import sd.rastreamentos.soap.ConsultaVeiculoID;
import sd.rastreamentos.soap.DeleteVeiculoID;
import sd.rastreamentos.soap.ListaPosicaoVeiculoID;
import sd.rastreamentos.soap.ListaTipoID;

/**
 *
 * @author Naiara
 */
public class InterfaceGráfica1 extends javax.swing.JFrame {
    private Veiculo veiculo;

    public Veiculo getVeiculo() {
        return veiculo;
    }

    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    
    private DefaultTableModel dtm_consultar;
    private DefaultTableModel dtm_listarTipo;
    private DefaultTableModel dtm_listarPosicao;
    /**
     * Creates new form InterfaceGráfica1
     */
    public InterfaceGráfica1() {
        initComponents();
        dtm_consultar = (DefaultTableModel) tabela_con.getModel();
        dtm_consultar.setNumRows(0);
        dtm_listarTipo = (DefaultTableModel) tabela_listarTipo.getModel();
        dtm_listarTipo.setNumRows(0);
        dtm_listarPosicao = (DefaultTableModel) tabela_listarPosicao.getModel();
        dtm_listarPosicao.setNumRows(0);
    }
    private void inserirItemTabela(Veiculo v, DefaultTableModel dtm) {
        dtm.addRow(new Object[]{
            v.getCodigo(),
            v.getPlaca(),
            v.getTipo(),
            v.getCapacidade(),
            v.getUnpac(),
        });
    }
    private void inserirItemTabela2(Posicao p, DefaultTableModel dtm) {
        dtm.addRow(new Object[]{
            p.getVeiculo().getCodigo(),
            p.getDatahora(),
            p.getLatitude(),
            p.getLongitude()
        });
    }
     private void attTabela(DefaultTableModel dtm){
         dtm.setNumRows(0);
     }
    /**
     * Creates new form InterfaceGráfica
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_guias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        label_cod_add = new javax.swing.JLabel();
        texto_placa_add = new javax.swing.JTextField();
        label_placa_add = new javax.swing.JLabel();
        label_tipo_add = new javax.swing.JLabel();
        label_cap_add = new javax.swing.JLabel();
        label_unpac_add = new javax.swing.JLabel();
        texto_cod_add = new javax.swing.JTextField();
        texto_tipo_add = new javax.swing.JTextField();
        texto_unpac_add = new javax.swing.JTextField();
        texto_cap_add = new javax.swing.JTextField();
        btn_enviar_add = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        label_cod_alt = new javax.swing.JLabel();
        texto_placa_alt = new javax.swing.JTextField();
        label_placa_alt = new javax.swing.JLabel();
        label_tipo_alt = new javax.swing.JLabel();
        label_cap_alt = new javax.swing.JLabel();
        label_unpac_alt = new javax.swing.JLabel();
        texto_cod_alt = new javax.swing.JTextField();
        texto_tipo_alt = new javax.swing.JTextField();
        texto_unpac_alt = new javax.swing.JTextField();
        texto_cap_alt = new javax.swing.JTextField();
        btn_enviar_alt = new javax.swing.JButton();
        btn_buscar_alt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_cod_con = new javax.swing.JLabel();
        texto_cod_con = new javax.swing.JTextField();
        btn_buscar_con = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_con = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        label_cod_del = new javax.swing.JLabel();
        texto_cod_del = new javax.swing.JTextField();
        btn_excluir_del = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        label_tipo_listarTipo = new javax.swing.JLabel();
        texto_tipo_listarTipo = new javax.swing.JTextField();
        btn_buscar_listarTipo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela_listarTipo = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        label_cod_listarPosicao = new javax.swing.JLabel();
        texto_cod_listarPosicao = new javax.swing.JTextField();
        btn_buscar_listarPosicao = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_listarPosicao = new javax.swing.JTable();
        label_dia_listarPosicao = new javax.swing.JLabel();
        texto_dia_listarPosicao = new javax.swing.JTextField();
        label_mes_listarPosicao = new javax.swing.JLabel();
        texto_mes_listarPosicao = new javax.swing.JTextField();
        label_ano_listarPosicao = new javax.swing.JLabel();
        texto_ano_listarPosicao = new javax.swing.JTextField();
        label_hora_listarPosicao = new javax.swing.JLabel();
        texto_hora_listarPosicao = new javax.swing.JTextField();
        texto_min_listarPosicao = new javax.swing.JTextField();
        label_min_listarPosicao = new javax.swing.JLabel();
        label_seg_listarPosicao = new javax.swing.JLabel();
        texto_seg_listarPosicao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_cod_add.setText("Código");

        label_placa_add.setText("Placa");

        label_tipo_add.setText("Tipo");

        label_cap_add.setText("Capacidade");

        label_unpac_add.setText("Unpac");

        btn_enviar_add.setText("Enviar");
        btn_enviar_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cap_add)
                            .addComponent(label_unpac_add)
                            .addComponent(label_placa_add)
                            .addComponent(label_cod_add)
                            .addComponent(label_tipo_add))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_unpac_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_tipo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_cod_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_placa_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_cap_add, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_enviar_add)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cod_add)
                    .addComponent(texto_cod_add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_placa_add)
                    .addComponent(texto_placa_add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo_add)
                    .addComponent(texto_tipo_add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cap_add)
                    .addComponent(texto_cap_add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_unpac_add)
                    .addComponent(texto_unpac_add, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_enviar_add)
                .addContainerGap())
        );

        painel_guias.addTab("Adicionar", jPanel1);

        label_cod_alt.setText("Código");

        label_placa_alt.setText("Placa");

        label_tipo_alt.setText("Tipo");

        label_cap_alt.setText("Capacidade");

        label_unpac_alt.setText("Unpac");

        btn_enviar_alt.setText("Enviar");
        btn_enviar_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_altActionPerformed(evt);
            }
        });

        btn_buscar_alt.setText("Buscar");
        btn_buscar_alt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_altActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_enviar_alt))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cap_alt)
                            .addComponent(label_unpac_alt)
                            .addComponent(label_placa_alt)
                            .addComponent(label_tipo_alt)
                            .addComponent(label_cod_alt))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto_cod_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_unpac_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_tipo_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_placa_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texto_cap_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_buscar_alt)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cod_alt)
                    .addComponent(texto_cod_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_alt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_placa_alt)
                    .addComponent(texto_placa_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo_alt)
                    .addComponent(texto_tipo_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cap_alt)
                    .addComponent(texto_cap_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_unpac_alt)
                    .addComponent(texto_unpac_alt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_enviar_alt)
                .addContainerGap())
        );

        painel_guias.addTab("Alterar", jPanel3);

        label_cod_con.setText("Código");

        btn_buscar_con.setText("Buscar");
        btn_buscar_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_conActionPerformed(evt);
            }
        });

        tabela_con.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Placa", "Tipo", "Capacidade", "Unpac"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_con);
        if (tabela_con.getColumnModel().getColumnCount() > 0) {
            tabela_con.getColumnModel().getColumn(3).setHeaderValue("Capacidade");
            tabela_con.getColumnModel().getColumn(4).setHeaderValue("Unpac");
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(label_cod_con)
                .addGap(18, 18, 18)
                .addComponent(texto_cod_con, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_buscar_con)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cod_con)
                    .addComponent(texto_cod_con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_con))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        painel_guias.addTab("Consultar", jPanel2);

        label_cod_del.setText("Código");

        texto_cod_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_cod_delActionPerformed(evt);
            }
        });

        btn_excluir_del.setText("Excluir");
        btn_excluir_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(label_cod_del)
                .addGap(33, 33, 33)
                .addComponent(texto_cod_del, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btn_excluir_del)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cod_del)
                    .addComponent(texto_cod_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir_del))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        painel_guias.addTab("Deletar", jPanel4);

        label_tipo_listarTipo.setText("Tipo");

        btn_buscar_listarTipo.setText("Buscar");
        btn_buscar_listarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_listarTipoActionPerformed(evt);
            }
        });

        tabela_listarTipo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Placa", "Tipo", "Capacidade", "Unpac"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabela_listarTipo);
        if (tabela_listarTipo.getColumnModel().getColumnCount() > 0) {
            tabela_listarTipo.getColumnModel().getColumn(3).setHeaderValue("Capacidade");
            tabela_listarTipo.getColumnModel().getColumn(4).setHeaderValue("Unpac");
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(label_tipo_listarTipo)
                .addGap(18, 18, 18)
                .addComponent(texto_tipo_listarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_buscar_listarTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_tipo_listarTipo)
                    .addComponent(texto_tipo_listarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_listarTipo))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        painel_guias.addTab("Listar Tipo Veículo", jPanel5);

        label_cod_listarPosicao.setText("Código");

        btn_buscar_listarPosicao.setText("Buscar");
        btn_buscar_listarPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_listarPosicaoActionPerformed(evt);
            }
        });

        tabela_listarPosicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data/Hora", "Latitude", "Longitude"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela_listarPosicao);

        label_dia_listarPosicao.setText("Dia");

        label_mes_listarPosicao.setText("Mês");

        label_ano_listarPosicao.setText("Ano");

        label_hora_listarPosicao.setText("Hora");

        label_min_listarPosicao.setText("Minuto");

        label_seg_listarPosicao.setText("Segundo");

        texto_seg_listarPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_seg_listarPosicaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cod_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_dia_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_ano_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_mes_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texto_ano_listarPosicao, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(texto_mes_listarPosicao)
                            .addComponent(texto_dia_listarPosicao)
                            .addComponent(texto_cod_listarPosicao))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_hora_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_min_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_seg_listarPosicao))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(texto_seg_listarPosicao)
                            .addComponent(texto_hora_listarPosicao)
                            .addComponent(texto_min_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btn_buscar_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_cod_listarPosicao)
                            .addComponent(texto_cod_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btn_buscar_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(texto_dia_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_hora_listarPosicao))
                                    .addComponent(label_dia_listarPosicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(texto_mes_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_min_listarPosicao))
                                    .addComponent(label_mes_listarPosicao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_ano_listarPosicao)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(texto_ano_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label_seg_listarPosicao))))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(texto_hora_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(texto_min_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(texto_seg_listarPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        painel_guias.addTab("Listar Posição Veículo", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_guias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviar_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_altActionPerformed
        // TODO add your handling code here:
                boolean flag = true;
        
        if(flag){
            if(!texto_placa_alt.getText().isEmpty()){
                veiculo.setPlaca(texto_placa_alt.getText());
                veiculo.setTipo(Integer.parseInt(texto_tipo_alt.getText()));
                veiculo.setCapacidade(Integer.parseInt(texto_cap_alt.getText()));
                veiculo.setUnpac(texto_unpac_alt.getText());

                if(veiculo.getPlaca().length() > 7){
                    JOptionPane.showMessageDialog(this, "Placa length > 7!");
                    flag = false;
                }
                if(veiculo.getUnpac().length() > 5){
                    JOptionPane.showMessageDialog(this, "Unpac length > 5!");
                    flag = false;
                }                
            }
            else
                flag = false;
        }
        
        if(flag){
            //tenta alterar o veiculo
                if(AlteraVeiculoID.AleteraVeiculo(veiculo)){
                    JOptionPane.showMessageDialog(this, "Alterado com sucesso!");
                limparCampos("alt");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Erro ao Alterar");
                }
                
        }

    }//GEN-LAST:event_btn_enviar_altActionPerformed

    private void btn_enviar_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_addActionPerformed
        // TODO add your handling code here:
        boolean flag = true;
            Veiculo v = new Veiculo();
        
        if(flag){

            v.setCodigo(Integer.parseInt(texto_cod_add.getText()));
            v.setPlaca(texto_placa_add.getText());
            v.setTipo(Integer.parseInt(texto_tipo_add.getText()));
            v.setCapacidade(Integer.parseInt(texto_cap_add.getText()));
            v.setUnpac(texto_unpac_add.getText());

            if(v.getPlaca().length() > 7){
                JOptionPane.showMessageDialog(this, "Placa length > 7!");
                flag = false;
            }
            if(v.getUnpac().length() > 5){
                JOptionPane.showMessageDialog(this, "Unpac length > 5!");
                flag = false;
            }
        }
        
        if(flag){
            //tenta inserir o veiculo
            if(AddVeiculo.AdicionaVeiculo(v)){
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso!");
                limparCampos("add");
            }
            else
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar");
            
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar");
        }
        
    }//GEN-LAST:event_btn_enviar_addActionPerformed

    private void btn_buscar_altActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_altActionPerformed
        // TODO add your handling code here:
        Integer codigo = verificarDigitos(texto_cod_alt.getText());
        if(codigo == null){
            texto_cod_alt.setText("");
            return;
        }
            
        veiculo = ConsultaVeiculoID.ConsultaVeiculo(codigo);
        if (veiculo != null) {
            texto_placa_alt.setText(veiculo.getPlaca());
            texto_tipo_alt.setText(String.valueOf(veiculo.getTipo()));
            texto_cap_alt.setText(String.valueOf(veiculo.getCapacidade()));
            texto_unpac_alt.setText(veiculo.getUnpac());
        } else {
            JOptionPane.showMessageDialog(this, "Código Não encontrado");
        }
    }//GEN-LAST:event_btn_buscar_altActionPerformed

    private void btn_buscar_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_conActionPerformed
        // TODO add your handling code here:
        Integer codigo = verificarDigitos(texto_cod_con.getText());
        if(codigo == null){
            texto_cod_con.setText("");
            return;
        }
        attTabela(dtm_consultar);
        veiculo = null;
        veiculo = ConsultaVeiculoID.ConsultaVeiculo(codigo);

        if (veiculo != null) {
            inserirItemTabela(veiculo, dtm_consultar);
        } else {
            JOptionPane.showMessageDialog(rootPane, "O código não foi encontrado");
        }       
    }//GEN-LAST:event_btn_buscar_conActionPerformed

    private void texto_cod_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_cod_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_cod_delActionPerformed

    private void btn_excluir_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_delActionPerformed
        // TODO add your handling code here:
        if (texto_cod_del.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Campo cógigo é obrigatório!");
            return;
        }

        veiculo = ConsultaVeiculoID.ConsultaVeiculo(Integer.parseInt(texto_cod_del.getText()));

        if (veiculo == null) {
            JOptionPane.showMessageDialog(this, "O veiculo informado não existe");
            texto_cod_del.setText("");
        } else {
            if (DeleteVeiculoID.DeletaVeiculo(Integer.parseInt(texto_cod_del.getText()))) {
                JOptionPane.showMessageDialog(this, "Veiculo excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir veiculo");
            }
            texto_cod_del.setText("");
        }
    }//GEN-LAST:event_btn_excluir_delActionPerformed

    private void btn_buscar_listarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_listarTipoActionPerformed
        // TODO add your handling code here:
        Integer tipo = verificarDigitos(texto_tipo_listarTipo.getText());
        if(tipo == null){
            texto_tipo_listarTipo.setText("");
            return;
        }
        attTabela(dtm_listarTipo);
        List<Veiculo> ls = ListaTipoID.ListaTipo(tipo);
        
        try {
            for (Veiculo v : ls) {
                inserirItemTabela(v, dtm_listarTipo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "O código não foi encontrado");
        }
    }//GEN-LAST:event_btn_buscar_listarTipoActionPerformed

    private void texto_seg_listarPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_seg_listarPosicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_seg_listarPosicaoActionPerformed

    private void btn_buscar_listarPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_listarPosicaoActionPerformed
        // TODO add your handling code here:

        if(!texto_cod_listarPosicao.getText().isEmpty()){
            Integer codigo = Integer.parseInt(texto_cod_listarPosicao.getText());
            List<Posicao> ls = null;

            if(!texto_dia_listarPosicao.getText().isEmpty())
            {
                GregorianCalendar cal = new GregorianCalendar();
                cal.set(Calendar.YEAR, Integer.parseInt(texto_ano_listarPosicao.getText()));
                cal.set(Calendar.MONTH, Integer.parseInt(texto_mes_listarPosicao.getText())-1);
                cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(texto_dia_listarPosicao.getText()));
                cal.set(Calendar.HOUR_OF_DAY, Integer.parseInt(texto_hora_listarPosicao.getText()));
                cal.set(Calendar.MINUTE, Integer.parseInt(texto_min_listarPosicao.getText()));
                cal.set(Calendar.SECOND, Integer.parseInt(texto_seg_listarPosicao.getText()));
                try{
                    XMLGregorianCalendar xmlDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(cal);
                    ls = ListaPosicaoVeiculoID.ListaPosicao(codigo, xmlDate);
                } catch (DatatypeConfigurationException ex) {
                    Logger.getLogger(InterfaceGráfica1.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            else{
                ls = ListaPosicaoVeiculoID.ListaPosicao(codigo, null);
            }

            attTabela(dtm_listarPosicao);
            for (Posicao p : ls) {
                inserirItemTabela2(p, dtm_listarPosicao);
            }

        }

    }//GEN-LAST:event_btn_buscar_listarPosicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGráfica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceGráfica1().setVisible(true);
        });
    }
    
    private void limparCampos(String tab){
        if(tab == "add"){
            texto_cod_add.setText("");
            texto_placa_add.setText("");
            texto_tipo_add.setText("");
            texto_cap_add.setText("");
            texto_unpac_add.setText("");
        }else if(tab == "alt"){
            texto_cod_alt.setText("");
            texto_placa_alt.setText("");
            texto_tipo_alt.setText("");
            texto_cap_alt.setText("");
            texto_unpac_alt.setText("");
        }
    }
    
    private Integer verificarDigitos(String texto){
        Integer c = null ;
        try {
            c = Integer.parseInt(texto);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Código: '" + texto + "' inválido! Digite apenas números.");
            return null;
        }
        return c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar_alt;
    private javax.swing.JButton btn_buscar_con;
    private javax.swing.JButton btn_buscar_listarPosicao;
    private javax.swing.JButton btn_buscar_listarTipo;
    private javax.swing.JButton btn_enviar_add;
    private javax.swing.JButton btn_enviar_alt;
    private javax.swing.JButton btn_excluir_del;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_ano_listarPosicao;
    private javax.swing.JLabel label_cap_add;
    private javax.swing.JLabel label_cap_alt;
    private javax.swing.JLabel label_cod_add;
    private javax.swing.JLabel label_cod_alt;
    private javax.swing.JLabel label_cod_con;
    private javax.swing.JLabel label_cod_del;
    private javax.swing.JLabel label_cod_listarPosicao;
    private javax.swing.JLabel label_dia_listarPosicao;
    private javax.swing.JLabel label_hora_listarPosicao;
    private javax.swing.JLabel label_mes_listarPosicao;
    private javax.swing.JLabel label_min_listarPosicao;
    private javax.swing.JLabel label_placa_add;
    private javax.swing.JLabel label_placa_alt;
    private javax.swing.JLabel label_seg_listarPosicao;
    private javax.swing.JLabel label_tipo_add;
    private javax.swing.JLabel label_tipo_alt;
    private javax.swing.JLabel label_tipo_listarTipo;
    private javax.swing.JLabel label_unpac_add;
    private javax.swing.JLabel label_unpac_alt;
    private javax.swing.JTabbedPane painel_guias;
    private javax.swing.JTable tabela_con;
    private javax.swing.JTable tabela_listarPosicao;
    private javax.swing.JTable tabela_listarTipo;
    private javax.swing.JTextField texto_ano_listarPosicao;
    private javax.swing.JTextField texto_cap_add;
    private javax.swing.JTextField texto_cap_alt;
    private javax.swing.JTextField texto_cod_add;
    private javax.swing.JTextField texto_cod_alt;
    private javax.swing.JTextField texto_cod_con;
    private javax.swing.JTextField texto_cod_del;
    private javax.swing.JTextField texto_cod_listarPosicao;
    private javax.swing.JTextField texto_dia_listarPosicao;
    private javax.swing.JTextField texto_hora_listarPosicao;
    private javax.swing.JTextField texto_mes_listarPosicao;
    private javax.swing.JTextField texto_min_listarPosicao;
    private javax.swing.JTextField texto_placa_add;
    private javax.swing.JTextField texto_placa_alt;
    private javax.swing.JTextField texto_seg_listarPosicao;
    private javax.swing.JTextField texto_tipo_add;
    private javax.swing.JTextField texto_tipo_alt;
    private javax.swing.JTextField texto_tipo_listarTipo;
    private javax.swing.JTextField texto_unpac_add;
    private javax.swing.JTextField texto_unpac_alt;
    // End of variables declaration//GEN-END:variables
}
